version: '3.3'
services:
  exchange-rate-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "52002:52002"
    networks:
      - default

  transaction-service:
    image: dothuhang/exchange-transaction-api
    ports:
      - "52003:52003"
    networks:
      - default
    depends_on:
      - exchange-rate-service
networks:
  default: